[tool.poetry]
name = "aws-cloudfront-ip-ranges"
version = "0.1.0"
description = ""
authors = ["Ryan Reece <ryan@reece.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
